In [7]:
# 1. Basic List Comprehensions

# Traditional loop approach
numbers = list(range(1, 21))
even_traditional = []
for num in numbers:
    if num % 2 == 0:
        even_traditional.append(num)

# List comprehension approach
even_comprehension = [num for num in numbers if num % 2 == 0]
print(f"Original numbers: {numbers}")
print(f"Evens (traditional): {even_traditional}")
print(f"Evens (comprehension): {even_comprehension}")

# More examples of filtering
words = ["apple", "banana", "cherry", "date", "kiwi", "mango"]

# Only keep words with length greater than 4
long_words = [word for word in words if len(word) > 4]
print(f"\nOriginal words: {words}")
print(f"Words longer than 5 letters: {long_words}")

# Squares of odd numbers only
odd_squares = [n ** 2 for n in numbers if n % 2 != 0]
print(f"\nSquares of odd numbers: {odd_squares}")

# Conditional expressions inside comprehension
labels = ["even" if n % 2 == 0 else "odd" for n in range(1, 11)]
print(f"\nNumber labels (1-10): {labels}")

Original numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Evens (traditional): [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
Evens (comprehension): [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

Original words: ['apple', 'banana', 'cherry', 'date', 'kiwi', 'mango']
Words longer than 5 letters: ['apple', 'banana', 'cherry', 'mango']

Squares of odd numbers: [1, 9, 25, 49, 81, 121, 169, 225, 289, 361]

Number labels (1-10): ['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even']

In [8]:
# 2. List Comprehensions with Filtering

# Filter odd numbers and square them
numbers = list(range(1, 16))
odd_squares = [num ** 2 for num in numbers if num % 2 != 0]
print(f"Numbers: {numbers}")
print(f"Odd squares: {odd_squares}")

# Filter and transform names
names = ["Aayushi", "Rahul", "Anushka", "Karan", "Sona", "Arjun", "Meera", "Siddharth"]
long_names_upper = [name.upper() for name in names if len(name) > 5]
short_names_lower = [name.lower() for name in names if len(name) <= 4]
print(f"\nAll names: {names}")
print(f"Long names (uppercase): {long_names_upper}")
print(f"Short names (lowercase): {short_names_lower}")

# Working with student records
students = [
    {"name": "Aayushi", "marks": 88, "passed": True},
    {"name": "Rahul", "marks": 45, "passed": False},
    {"name": "Anushka", "marks": 92, "passed": True},
    {"name": "Karan", "marks": 38, "passed": False},
    {"name": "Sona", "marks": 76, "passed": True},
    {"name": "Arjun", "marks": 81, "passed": True}
]

# Extract names of students who passed
passed_students = [s["name"] for s in students if s["passed"]]

# Get marks of students who scored more than 80
top_scores = [s["marks"] for s in students if s["marks"] > 80]
print(f"\nPassed students: {passed_students}")
print(f"Top scores (>80): {top_scores}")

# Multiple conditions with transformation
honors_students = [
    s["name"].upper() 
    for s in students 
    if s["marks"] > 75 and s["passed"]
]
print(f"Honors students (marks >75 & passed): {honors_students}")

Numbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Odd squares: [1, 9, 25, 49, 81, 121, 169, 225]

All names: ['Aayushi', 'Rahul', 'Anushka', 'Karan', 'Sona', 'Arjun', 'Meera', 'Siddharth']
Long names (uppercase): ['AAYUSHI', 'ANUSHKA', 'SIDDHARTH']
Short names (lowercase): ['sona']

Passed students: ['Aayushi', 'Anushka', 'Sona', 'Arjun']
Top scores (>80): [88, 92, 81]
Honors students (marks >75 & passed): ['AAYUSHI', 'ANUSHKA', 'SONA', 'ARJUN']

In [16]:
# 3. Dictionary Comprehensions

# Create a dictionary of cubes
numbers = [1, 2, 3, 4, 5, 6, 7]
cubes_dict = {num: num ** 3 for num in numbers}

print(f"Numbers to cubes: {cubes_dict}")

# Create dictionary from two lists
cities = ["Mumbai", "Delhi", "Bengaluru", "Chennai"]
populations = [20_000_000, 18_600_000, 12_500_000, 10_900_000]

city_populations = {city: pop for city, pop in zip(cities, populations)}
print(f"\nCity populations: {city_populations}")

# Transform existing dictionary
student_scores = {"Aayushi": 88, "Rahul": 45, "Anushka": 92, "Karan": 38, "Sona": 76}

# Pass/Fail status
status = {name: ("Pass" if score >= 50 else "Fail") for name, score in student_scores.items()}
print(f"\nStudent scores: {student_scores}")
print(f"Pass/Fail status: {status}")

# Dictionary comprehension with filtering
top_students = {name: score for name, score in student_scores.items() if score >= 80}
print(f"Top students (>= 80): {top_students}")

# Invert dictionary (swap keys and values)
score_to_student = {score: name for name, score in student_scores.items()}
print(f"Score to student mapping: {score_to_student}")

# Working with string data
employee_data = [
    "Karan:IT:85000", 
    "Riya:HR:65000", 
    "Siddharth:Finance:95000", 
    "Neha:Marketing:72000"
]

# Parse and create dictionary (name â†’ salary)
employee_salaries = {
    parts[0]: int(parts[2])
    for line in employee_data
    for parts in [line.split(":")]
}
print(f"\nEmployee salaries: {employee_salaries}")

Numbers to cubes: {1: 1, 2: 8, 3: 27, 4: 64, 5: 125, 6: 216, 7: 343}

City populations: {'Mumbai': 20000000, 'Delhi': 18600000, 'Bengaluru': 12500000, 'Chennai': 10900000}

Student scores: {'Aayushi': 88, 'Rahul': 45, 'Anushka': 92, 'Karan': 38, 'Sona': 76}
Pass/Fail status: {'Aayushi': 'Pass', 'Rahul': 'Fail', 'Anushka': 'Pass', 'Karan': 'Fail', 'Sona': 'Pass'}
Top students (>= 80): {'Aayushi': 88, 'Anushka': 92}
Score to student mapping: {88: 'Aayushi', 45: 'Rahul', 92: 'Anushka', 38: 'Karan', 76: 'Sona'}

Employee salaries: {'Karan': 85000, 'Riya': 65000, 'Siddharth': 95000, 'Neha': 72000}

In [10]:
# 4. Nested Comprehensions

# Create a table of squares (1-5)
squares_table = [[i ** 2 for j in range(1, 6)] for i in range(1, 6)]
print("Squares table (1-5):")
for row in squares_table:
    print(row)

# Flatten a 2D list of marks
marks_matrix = [
    [85, 90, 78],
    [88, 76, 92],
    [70, 80, 65]
]
flattened_marks = [mark for row in marks_matrix for mark in row]
print(f"\nOriginal marks matrix: {marks_matrix}")
print(f"Flattened marks: {flattened_marks}")

# Process nested data structures
students_by_class = [
    {
        "class": "10A",
        "students": [
            {"name": "Aayushi", "marks": 88},
            {"name": "Rahul", "marks": 45},
            {"name": "Anushka", "marks": 92}
        ]
    },
    {
        "class": "10B",
        "students": [
            {"name": "Karan", "marks": 38},
            {"name": "Sona", "marks": 76},
            {"name": "Arjun", "marks": 81}
        ]
    }
]

# Extract all student names across classes
all_student_names = [
    student["name"]
    for cls in students_by_class
    for student in cls["students"]
]

# Extract students with marks > 75 across classes
top_students = [
    student["name"]
    for cls in students_by_class
    for student in cls["students"]
    if student["marks"] > 75
]
print(f"\nAll students: {all_student_names}")
print(f"Top students (>75): {top_students}")

# Create nested dictionary with class summaries
class_summary = {
    cls["class"]: {
        "total_marks": sum(stu["marks"] for stu in cls["students"]),
        "avg_marks": sum(stu["marks"] for stu in cls["students"]) / len(cls["students"]),
        "student_count": len(cls["students"])
    }
    for cls in students_by_class
}
print(f"\nClass summary: {class_summary}")

Squares table (1-5):
[1, 1, 1, 1, 1]
[4, 4, 4, 4, 4]
[9, 9, 9, 9, 9]
[16, 16, 16, 16, 16]
[25, 25, 25, 25, 25]

Original marks matrix: [[85, 90, 78], [88, 76, 92], [70, 80, 65]]
Flattened marks: [85, 90, 78, 88, 76, 92, 70, 80, 65]

All students: ['Aayushi', 'Rahul', 'Anushka', 'Karan', 'Sona', 'Arjun']
Top students (>75): ['Aayushi', 'Anushka', 'Sona', 'Arjun']

Class summary: {'10A': {'total_marks': 225, 'avg_marks': 75.0, 'student_count': 3}, '10B': {'total_marks': 195, 'avg_marks': 65.0, 'student_count': 3}}

In [11]:
# 5. Set Comprehensions

# Get unique first letters of names
names = ["Aayushi", "Rahul", "Anushka", "Karan", "Sona", "Arjun", "Meera", "Siddharth"]
unique_first_letters = {name[0] for name in names}
print(f"Names: {names}")
print(f"Unique first letters: {sorted(unique_first_letters)}")

# Student course enrollment data
enrollments = [
    {"name": "Aayushi", "course": "Math", "year": "2025"},
    {"name": "Rahul", "course": "Science", "year": "2025"},
    {"name": "Anushka", "course": "Math", "year": "2024"},
    {"name": "Karan", "course": "History", "year": "2025"},
    {"name": "Sona", "course": "Science", "year": "2024"},
    {"name": "Arjun", "course": "Math", "year": "2025"}
]

# Get unique courses
unique_courses = {record["course"] for record in enrollments}
print(f"\nUnique courses: {sorted(unique_courses)}")

# Get unique years
unique_years = {record["year"] for record in enrollments}
print(f"Unique years: {sorted(unique_years)}")

# Get unique students enrolled in Math
math_students = {record["name"] for record in enrollments if record["course"] == "Math"}
print(f"Students enrolled in Math: {sorted(math_students)}")

# Get unique course-year combinations
course_years = {f"{record['course']} ({record['year']})" for record in enrollments}
print(f"Course-year combinations: {sorted(course_years)}")

Names: ['Aayushi', 'Rahul', 'Anushka', 'Karan', 'Sona', 'Arjun', 'Meera', 'Siddharth']
Unique first letters: ['A', 'K', 'M', 'R', 'S']

Unique courses: ['History', 'Math', 'Science']
Unique years: ['2024', '2025']
Students enrolled in Math: ['Aayushi', 'Anushka', 'Arjun']
Course-year combinations: ['History (2025)', 'Math (2024)', 'Math (2025)', 'Science (2024)', 'Science (2025)']

In [17]:
# Exercise 1: Data transformation with filtering
sensor_readings = [
    "23.5", "24.1", "invalid", "22.8", "25.0", "error", "23.9", "24.3", "22.5"
]

# Creating a list comprehension
valid_readings = [
    float(r) 
    for r in sensor_readings 
    if r.replace(".", "", 1).isdigit() and 22.0 <= float(r) <= 25.0
]

print(f"Valid readings: {valid_readings}")

Valid readings: [23.5, 24.1, 22.8, 25.0, 23.9, 24.3, 22.5]

In [18]:
# Exercise 2: Dictionary comprehension for data grouping
employee_records = [
    {"name": "Alice", "department": "Engineering", "salary": 75000},
    {"name": "Bob", "department": "Marketing", "salary": 65000},
    {"name": "Charlie", "department": "Engineering", "salary": 80000},
    {"name": "Diana", "department": "Sales", "salary": 70000},
    {"name": "Eve", "department": "Marketing", "salary": 68000}
]

# Get unique departments
departments = {emp["department"] for emp in employee_records}

# Dictionary comprehension: department â†’ average salary
dept_avg_salaries = {
    dept: sum(emp["salary"] for emp in employee_records if emp["department"] == dept) / 
          sum(1 for emp in employee_records if emp["department"] == dept)
    for dept in departments
}
print(f"Department average salaries: {dept_avg_salaries}")

Department average salaries: {'Sales': 70000.0, 'Engineering': 77500.0, 'Marketing': 66500.0}

In [19]:
# Exercise 3: Nested comprehension for matrix operations
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

# Add corresponding elements of matrix_a and matrix_b
matrix_sum = [
    [a + b for a, b in zip(row_a, row_b)]
    for row_a, row_b in zip(matrix_a, matrix_b)
]
print(f"Matrix sum: {matrix_sum}")

# Transpose matrix_a 
transposed = [
    [matrix_a[row][col] for row in range(len(matrix_a))]
    for col in range(len(matrix_a[0]))
]
print(f"Transposed matrix: {transposed}")

Matrix sum: [[10, 10, 10], [10, 10, 10], [10, 10, 10]]
Transposed matrix: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]